# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=140)),
                ('album_cover', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=140)),
                ('journal_details', models.TextField()),
                ('date', models.DateTimeField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Album')),
            ],
        ),
    ]
