# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20170116_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_image',
            field=models.FileField(upload_to=''),
        ),
    ]
