# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170120_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='date',
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
