# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170121_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date',
            field=models.TextField(default='0000000'),
        ),
        migrations.AddField(
            model_name='journal',
            name='time',
            field=models.TextField(default='0000000'),
        ),
    ]
