# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-29 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20170129_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='journal',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
